{% set version = "1.0" %}

package:
  name: contextily
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/contextily/contextily-{{ version }}.tar.gz
  sha256: 338f5669110b06134afa60c536fef9bb880d683dd8931d5ff9ef7cfaf3ca2952

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - geopy
    - joblib
    - matplotlib-base
    - mercantile
    - pillow
    - rasterio
    - requests

test:
  imports:
    - contextily

about:
  home: https://github.com/geopandas/contextily
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Context geo-tiles in Python'
  license_family: BSD

extra:
  recipe-maintainers:
    - darribas
    - ocefpaf
    - jorisvandenbossche
    - ljwolf
